### ISSUE TITLE
首页报错

### ISSUE THREAD

**Issue by wxhscc** [HyperLife1119/OnChat#2]
Warning: require(/www/wwwroot/web/public/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/web/public/index.php on line 15

找不到启动文件是什么原因  vendor/autoload.php

**Comment by HyperLife1119** [comment]
安装`composer`，进入项目根目录，在命令行输入`composer install`

**Comment by wxhscc** [comment]
> 安装`composer`，进入项目根目录，在命令行输入`composer install`
环境安装好后，访问提示 Running Successfully!  运行成功，但是没有跳转到登录页面，阿婆主可以教教吗

**Comment by HyperLife1119** [comment]
这个项目分为前后两端，当前项目仓库属于后端部分，[前端仓库在此](https://github.com/HyperLife1119/OnChat-Web)，等我有空写份makedown文档出来吧...
