### ISSUE TITLE
install

### ISSUE THREAD

**Issue by pepekayu** [HyperLife1119/OnChat#28]
Sir, can you make a video about the installation?  Although I read the steps, I did not know how to set up, I really liked this system you made, it was a great thing, thank you.

**Comment by HyperLife1119** [comment]
Due to busy work recently, the tutorial video cannot be recorded.  I think you can put the questions you have encountered to me here, and I will help answer them.

**Comment by pepekayu** [comment]
> Due to busy work recently, the tutorial video cannot be recorded. I think you can put the questions you have encountered to me here, and I will help answer them.

I know how to set up a normal php script but I did not know how to set up your system.  Could it be a centos or ubuntu server?  Can you write step by step how to install this system on the server?  Let's say the server is ready, after this stage, how will I install it, where will I add the codes. Thanks

**Comment by pepekayu** [comment]
Sir, if I send you the server information, would you install it?

**Comment by HyperLife1119** [comment]
I think you should read the documentation first. https://docs.chat.hypergo.net/docs/intro
