### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by pepekayu** [HyperLife1119/OnChat#33]
Does the php version work in php 7.2?  Is php 7.1 mandatory?

**Comment by HyperLife1119** [comment]
Oh, the content of the document may be a bit lagging.  OnChat should support PHP 7.2+ at least.

**Comment by pepekayu** [comment]
> Belgenin içeriği biraz gecikmiş olabilir. OnChat en azından PHP 7.2+ ' yı desteklemelidir.

When you are available, we expect you to shoot a video showing how the installation is done. The written explanation on your site does not understand much. Since the installation content on your site is in Chinese, it is very confusing. However, if the visual installation is a video, it can be understood no matter what language it is.

**Comment by pepekayu** [comment]
> Oh, the content of the document may be a bit lagging. OnChat should support PHP 7.2+ at least.

When you are available, we expect you to shoot a video showing how the installation is done. The written explanation on your site does not understand much. Since the installation content on your site is in Chinese, it is very confusing. However, if the visual installation is a video, it can be understood no matter what language it is.

**Comment by HyperLife1119** [comment]
I think I will record an installation video or write an English version of the document in the future. You can add stars⭐ to this project to keep an eye on the progress.
