### ISSUE TITLE
Swoole

### ISSUE THREAD

**Issue by pepekayu** [HyperLife1119/OnChat#37]
swoole is not working with the latest version, if it is 4.6 I have not been able to install it.

**Comment by HyperLife1119** [comment]
Sorry, PHP version should be at least 7.4.
https://github.com/HyperLife1119/OnChat/issues/33#issuecomment-1004252846

**Comment by pepekayu** [comment]
no it's not, your codes are incompatible with swoole version 4.8.

**Comment by HyperLife1119** [comment]
Please post the error message.

**Comment by pepekayu** [comment]
> Please post the error message.

When running composer, these codes warn that it requires swoole 4.6, but I can't manage to install swoole 4.6 version.


Sir, I will give you the server information and ssh information, I would be glad if you install onchat and the necessary plugin.  I am thinking of adding as translation for this system in different languages ​​and few designs.  As I said, I could not manage the server add-ons and you to set up this system.

**Comment by HyperLife1119** [comment]
I think you can tell me why you can't install Swoole 4.6.
If you use Windows OS, you can use Windows WSL.
